In [4]:
import torch
from torch.autograd import Variable

a=Variable(torch.Tensor([2,3]),requires_grad=True)
b=a+3
c=b*3
out=c.mean()
out.backward()      # 对a求导
print('input:')
print(a.data)
print('output:')
print(out.data.item()) # 计算（5+6）*3/2=16.5
print('input gradients are')
print(a.grad)

input:
tensor([2., 3.])
output:
16.5
input gradients are
tensor([1.5000, 1.5000])


In [13]:
import torch
from torch.autograd import Variable
import copy
a=Variable(torch.FloatTensor([[2.,4.]]),requires_grad=True)
b=torch.zeros(1,2)
b[0,0]=a[0,0]**2+a[0,1]
b[0,1]=a[0,1]**3+2*a[0,0]
out=2*b
# 其参数要传入和out维度一样的矩阵
out.backward(torch.FloatTensor([[1,0]]),retain_graph=True)
A_temp=copy.deepcopy(a.grad)
a.grad.zero_()
out.backward(torch.FloatTensor([[0,1]]))
B_temp=a.grad
print('jacobian matrix is:')
print(torch.cat((A_temp,B_temp),0))


jacobian matrix is:
tensor([[ 8.,  2.],
        [ 4., 96.]])
