两个矩阵按元素相乘：

In [1]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

# 2.3.6 降维
求和

In [2]:
A,A.shape,A.sum() # 所有元素求和

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 torch.Size([5, 4]),
 tensor(190.))

按照某一维度进行求和

In [3]:
A_sum_axis0=A.sum(axis=0) # 对每一列的所有行求和
A_sum_axis0,A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [4]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [5]:
# 沿着行和列对矩阵求和，等价于对矩阵的所有元素进行求和
A.sum(axis=[0,1]) 

tensor(190.)

求平均值；两种方法，一种用自带的函数，另一种通过将总和除以元素总数来计算平均值

In [6]:
A.mean(),A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [7]:
# 同样，计算平均值的函数也可以沿指定轴降低张量的维度。
A.mean(axis=0), A.sum(axis=0) / A.shape[0]


(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

## 非降维求和
有时，在调用函数来计算总和或均值时保持轴数不变会很有用

In [8]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

# 2.3.7 点积

In [11]:
x = torch.arange(4,dtype = torch.float32)
y = torch.ones(4, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

# 2.3.8 矩阵-向量积

In [12]:
A, x, torch.mv(A, x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

# 2.3.9 矩阵-矩阵乘法

In [13]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

# 2.3.10 范数

二范数计算方法如下：

In [14]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

# 2.3.13 练习

4. 我们在本节中定义了形状 (2,3,4) 的张量X。len(X)的输出结果是什么？

In [19]:
X=torch.arange(24).reshape(2,3,4)
len(X),X
# 输出为2，是第0个维度的值

(2,
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]))

5. 对于任意形状的张量X,len(X)是否总是对应于X特定轴的长度?这个轴是什么?

In [25]:
Y=torch.arange(40).reshape(1,40)
len(Y),Y
# 总是第0轴的值

(1,
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
          36, 37, 38, 39]]))

6. 运行A/A.sum(axis=1)，看看会发生什么。你能分析原因吗？

In [29]:
A
A2=A.sum(axis=1)
A2
#A/A2 # 会报错，维度不匹配

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 1